# Generated by Django 5.0.7 on 2024-07-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_alter_problem_name_alter_problem_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
